# Generated by Django 3.2 on 2021-07-17 10:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('project_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('repo_link', models.CharField(max_length=144)),
                ('live_link', models.CharField(max_length=144)),
            ],
        ),
    ]
