# Generated by Django 3.2 on 2021-07-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwards_app', '0003_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_wise', models.IntegerField(blank=True, default=0)),
                ('usability_wise', models.IntegerField(blank=True, default=0)),
                ('design_wise', models.IntegerField(blank=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwards_app.project')),
            ],
        ),
    ]
