# Generated by Django 3.2 on 2021-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards_app', '0004_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='published_at',
            new_name='posted_on',
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.URLField(max_length=300),
        ),
    ]
