# Generated by Django 3.2 on 2021-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards_app', '0007_auto_20210717_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.TextField(default='HTML'),
            preserve_default=False,
        ),
    ]
