# Generated by Django 3.2 on 2021-07-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards_app', '0008_project_technologies_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
