# Generated by Django 3.2 on 2021-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards_app', '0011_auto_20210719_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='average_rate',
            new_name='aggregate_average_rate',
        ),
        migrations.AddField(
            model_name='rate',
            name='content_wise_average',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='rate',
            name='design_wise_average',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='rate',
            name='usability_wise_average',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
